"""
Django settings for proyectos project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
load_dotenv()
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# Sin SECRET_KEY, Django no puede firmar sesiones ni tokens CSRF. Antes quedaba
# en None y el fallo aparecía después, lejos de su causa; mejor fallar al arrancar.
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "Falta la variable de entorno SECRET_KEY. Defínela en proyectos/.env "
        "(local) o en las variables del servicio (despliegue)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Por defecto apagado: hay que pedirlo explícitamente con DEBUG=1, y solo tiene
# sentido en local. Antes estaba fijo en False y para depurar había que editar
# este archivo.
DEBUG = os.getenv("DEBUG", "0") == "1"

# Hosts admitidos, separados por comas. El valor por omisión ("*") es el que
# usa el despliegue: Railway asigna el dominio y lo cambia sin avisar. Si algún
# día el dominio es fijo, acotarlo aquí por entorno cierra el paso a los ataques
# por cabecera Host sin tocar el código.
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'contenido',
    'cuentas',
    'web',
    'cuentas_de_cobro'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los estáticos también con DEBUG=False (debe ir justo
    # después de SecurityMiddleware y antes del resto).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Después de WhiteNoise a propósito: los estáticos no lo atraviesan y
    # conservan su caché larga. Lo que sale de la aplicación, en cambio, no se
    # guarda en el navegador (ver el porqué en cuentas/middleware.py).
    'cuentas.middleware.SinCacheDeNavegador',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cuentas.context_processors.roles',
                'cuentas_de_cobro.context_processors.roles_cuentas_cobro',
                'web.context_processors.notificaciones_web',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectos.wsgi.application'


AWS_ACCESS_KEY_ID = os.getenv("SUPABASE_S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SUPABASE_S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("SUPABASE_BUCKET", "documentos")


# Endpoint S3 del proyecto de Supabase. Va por variable de entorno porque cambia
# al mover la plataforma de cuenta/proyecto; dejarlo fijo en el codigo obliga a
# tocar settings.py en cada migracion (y a recordar que estaba aqui escondido).
AWS_S3_ENDPOINT_URL = os.getenv("SUPABASE_S3_ENDPOINT_URL")
AWS_S3_REGION_NAME = os.getenv("SUPABASE_S3_REGION", "us-east-1")

# Supabase exige path-style + firma v4
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_SIGNATURE_VERSION = "s3v4"

# Bucket privado -> URLs firmadas (default). No lo pongas en False para docs sensibles.
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 3600  # segundos de validez del link firmado

# Evita que dos archivos con el mismo nombre se sobreescriban silenciosamente
AWS_S3_FILE_OVERWRITE = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "location": "media",  # prefijo dentro del bucket
        },
    },
    "staticfiles": {
        # WhiteNoise: comprime y versiona los estáticos (cache-busting).
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

if DEBUG:
    # En desarrollo, estáticos sin manifiesto. Con el manifiesto, cualquier
    # archivo nuevo o cambiado obliga a correr `collectstatic` antes de poder
    # abrir la página: si falta la entrada, Django lanza "Missing staticfiles
    # manifest entry" y la respuesta es un 500 (incluida la propia página de
    # error, que también extiende base.html).
    STORAGES["staticfiles"] = {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL,conn_max_age=600,)
}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-CO'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Carpeta donde collectstatic reúne los estáticos para que WhiteNoise los sirva.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Orígenes adicionales de confianza para CSRF. Solo hacen falta para peticiones
# de OTRO origen: Django ya acepta el origen propio de la petición, por eso la
# app funciona en su dominio aunque este no aparezca aquí. Formato
# "esquema://host", SIN barra final. Se configuran por entorno para no tener que
# tocar el código cada vez que cambia el dominio.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]

# Railway (y otros PaaS) terminan el TLS en su proxy y reenvían al contenedor por
# HTTP. Esto le dice a Django que la petición original era HTTPS, para que las
# comprobaciones de seguridad (CSRF, cookies, is_secure) usen el esquema correcto.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# --------------------------------------------------------------------------- #
# Endurecimiento HTTPS
# --------------------------------------------------------------------------- #
# Todo esto se apaga con HTTPS_ESTRICTO=0, que es lo que hace falta para correr
# en local por HTTP: con las cookies marcadas Secure el navegador no las envía
# por HTTP y no se puede ni iniciar sesión, y SECURE_SSL_REDIRECT provocaría un
# bucle de redirecciones.
HTTPS_ESTRICTO = os.getenv("HTTPS_ESTRICTO", "1") == "1"

# Las cookies de sesión y de CSRF solo viajan por HTTPS (nunca en claro).
SESSION_COOKIE_SECURE = HTTPS_ESTRICTO
CSRF_COOKIE_SECURE = HTTPS_ESTRICTO

# La cookie de sesión no se expone a JavaScript (mitiga el robo vía XSS).
SESSION_COOKIE_HTTPONLY = True

# No enviar las cookies en peticiones cross-site (mitiga CSRF).
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Redirigir HTTP -> HTTPS. Funciona detrás del proxy gracias a
# SECURE_PROXY_SSL_HEADER, definido arriba.
SECURE_SSL_REDIRECT = HTTPS_ESTRICTO

# HSTS: le indica al navegador que use HTTPS siempre para este dominio.
# OJO: el navegador RECUERDA esta cabecera durante todo el tiempo indicado, y no
# hay forma de retirársela a quien ya la recibió. Por eso arranca en 1 hora: si
# algo sale mal se corrige en una hora y no en un año. Una vez verificado que el
# sitio va bien por HTTPS, subir a 31536000 (un año) vía SECURE_HSTS_SECONDS.
# No se activan includeSubDomains ni preload: afectarían a dominios vecinos y
# son todavía más difíciles de revertir.
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600")) if HTTPS_ESTRICTO else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# No filtrar la URL completa como Referer hacia sitios externos.
SECURE_REFERRER_POLICY = "same-origin"

# Impedir que el navegador adivine el tipo de contenido de un archivo servido
# (relevante porque la plataforma sirve documentos subidos por usuarios).
SECURE_CONTENT_TYPE_NOSNIFF = True


# --------------------------------------------------------------------------- #
# Registro de eventos (logging)
# --------------------------------------------------------------------------- #
# El handler de consola que trae Django por defecto está filtrado por
# `require_debug_true`, y el de correo exige ADMINS configurado. Con DEBUG=False
# y sin ADMINS eso deja los errores 500 SIN rastro: no aparecen en los logs del
# servicio y el fallo solo se ve como una página de error en el navegador. Esta
# configuración manda todo a la salida estándar, que es de donde Railway (y
# cualquier PaaS) lee los logs.
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "estandar": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "consola": {
            "class": "logging.StreamHandler",
            "formatter": "estandar",
        },
    },
    "root": {"handlers": ["consola"], "level": "WARNING"},
    "loggers": {
        # `django.request` emite el traceback completo de cada 500 por este
        # camino, así que basta con no filtrarlo.
        "django": {
            "handlers": ["consola"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Media files (archivos subidos por los formuladores)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

# Autenticación (app web de negocio)
LOGIN_URL = "cuentas:login"
LOGIN_REDIRECT_URL = "web:dashboard"
LOGOUT_REDIRECT_URL = "cuentas:login"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Unfold (admin personalizado)
# https://unfoldadmin.com/docs/configuration/settings/
UNFOLD = {
    "SITE_TITLE": "Gestión de Proyectos",
    "SITE_HEADER": "Gestión de Proyectos",
    "SITE_SUBHEADER": "Banproe",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "14 165 233",
            "600": "2 132 199",
            "700": "3 105 161",
            "800": "7 89 133",
            "900": "12 74 110",
            "950": "8 47 73",
        },
    },
}
