# Generated by Django 5.2 on 2026-06-08 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(verbose_name='Nombre de la actividad')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha programada')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('ER', 'En revisión'), ('AJ', 'Requiere ajustes'), ('AP', 'Aprobada')], max_length=2)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_a', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_por', to=settings.AUTH_USER_MODEL, verbose_name='Asigando por')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='ActividadEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_version', models.IntegerField(verbose_name='Número de la versión')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que entregó')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.actividades', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad entrega',
                'verbose_name_plural': 'Actividades entrega',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del documento')),
                ('archivo', models.FileField(upload_to='', verbose_name='Archivo')),
                ('actividad_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.actividadentrega', verbose_name='Actividad entrega')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(verbose_name='Nombre del proyecto')),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asigando a')),
                ('creador_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='actividades',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.proyectos'),
        ),
        migrations.CreateModel(
            name='Revisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('resultado', models.CharField(choices=[('AP', 'Aprobada'), ('AJ', 'Requiere ajustes'), ('RE', 'Rechazada')], max_length=2)),
                ('actividad_entrega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contenido.actividadentrega', verbose_name='Actividad entrega')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='Subactividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.TextField(verbose_name='Nombre de la subactividad')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenido.actividades', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Subactividad',
                'verbose_name_plural': 'Subactividades',
            },
        ),
        migrations.AddConstraint(
            model_name='actividadentrega',
            constraint=models.UniqueConstraint(fields=('actividad', 'numero_version'), name='Actividad_version_unique'),
        ),
    ]
