# Generated by Django 5.2 on 2026-06-26 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoCargue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Vigencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vigencia', models.IntegerField(verbose_name='Vigencia')),
            ],
            options={
                'verbose_name': 'Vigencia',
                'verbose_name_plural': 'Vigencias',
            },
        ),
        migrations.CreateModel(
            name='CuentaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes de entrega')),
                ('estado_revisores', models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('RE', 'Rechazado')], max_length=2, null=True)),
                ('estado_supervisor', models.CharField(blank=True, choices=[('AP', 'Aprobado'), ('RE', 'Rechazado')], max_length=2, null=True)),
                ('fecha_radicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de radicación de la entrega')),
                ('fecha_aprobacion_revisores', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la entrega de documentos')),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.vigencia', verbose_name='Vigencia de entrega')),
            ],
            options={
                'verbose_name': 'Cuenta entrega',
                'verbose_name_plural': 'Cuentas entrega',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('JU', 'Jurídico'), ('AD', 'Administrativo'), ('TE', 'Técnico')], max_length=2)),
                ('estado', models.CharField(choices=[('AC', 'Activa'), ('DE', 'Declinada')], default='AC', max_length=2)),
                ('motivo_declinacion', models.TextField(blank=True, verbose_name='Motivo por el que no puede revisar')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Revisor asignado')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_hechas', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor que asigna')),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.cuentaentrega')),
            ],
            options={
                'verbose_name': 'Asignación de revisor',
                'verbose_name_plural': 'Asignaciones de revisor',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('numero_version', models.IntegerField(verbose_name='Número de la versión')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.cuentaentrega', verbose_name='Cuenta de entrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que entregó')),
            ],
            options={
                'verbose_name': 'Documento entrega',
                'verbose_name_plural': 'Documentos entrega',
            },
        ),
        migrations.CreateModel(
            name='RevisionCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('JU', 'Jurídico'), ('AD', 'Administrativo'), ('TE', 'Técnico')], max_length=2, verbose_name='Rol de revisión')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('resultado', models.CharField(choices=[('AP', 'Aprobado'), ('AJ', 'Requiere ajustes'), ('RE', 'Rechazado')], max_length=2)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuentas_de_cobro.asignacionrevisor', verbose_name='Asignación')),
                ('documento_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.documentoentrega', verbose_name='Documento entrega')),
            ],
            options={
                'verbose_name': 'Revisión',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.CreateModel(
            name='RevisionParaRadicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('resultado', models.CharField(choices=[('AP', 'Aprobado'), ('AJ', 'Requiere ajustes'), ('RE', 'Rechazado')], max_length=2)),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.cuentaentrega')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Revisión documento',
                'verbose_name_plural': 'Revisión documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentosCuentaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento', models.FileField(upload_to='cuentas_cobro/%Y/%m/', verbose_name='Documento')),
                ('documento_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.documentoentrega', verbose_name='Documento entrega')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.tipodocumentocargue', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Documento cuenta de cobro entrega',
                'verbose_name_plural': 'Documentos cuenta de cobro entrega',
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionrevisor',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'AC')), fields=('cuenta_entrega', 'rol'), name='una_asignacion_activa_por_rol'),
        ),
        migrations.AddConstraint(
            model_name='documentoentrega',
            constraint=models.UniqueConstraint(fields=('cuenta_entrega', 'numero_version'), name='cuenta_entrega_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='revisioncuentacobro',
            constraint=models.UniqueConstraint(fields=('documento_entrega', 'rol'), name='revision_unica_por_rol'),
        ),
        migrations.AddConstraint(
            model_name='documentoscuentacobro',
            constraint=models.UniqueConstraint(fields=('documento_entrega', 'tipo_documento'), name='documento_tipo_unico_por_entrega'),
        ),
    ]
