# Generated by Django 5.2 on 2026-06-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_de_cobro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaentrega',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre del trámite'),
        ),
        migrations.AddField(
            model_name='documentoscuentacobro',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentario de revisión (causal de devolución)'),
        ),
        migrations.AddField(
            model_name='documentoscuentacobro',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('AP', 'Aprobado'), ('RE', 'Rechazado'), ('NA', 'No aplica')], default='PE', max_length=2, verbose_name='Estado del documento'),
        ),
        migrations.CreateModel(
            name='EventoTrazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('etapa', models.CharField(choices=[('RAD', 'Radicación'), ('ASI', 'Asignación de revisores'), ('REV', 'Revisión'), ('SUP', 'Decisión del supervisor'), ('CIE', 'Cierre')], max_length=3, verbose_name='Etapa')),
                ('evento', models.CharField(max_length=255, verbose_name='Evento')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='cuentas_de_cobro.cuentaentrega', verbose_name='Cuenta de entrega')),
            ],
            options={
                'verbose_name': 'Evento de trazabilidad',
                'verbose_name_plural': 'Eventos de trazabilidad',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('IS', 'Informe de Supervisión'), ('CC', 'Certificado de Cumplimiento')], max_length=2, verbose_name='Tipo de documento de cierre')),
                ('documento', models.FileField(upload_to='cierres/%Y/%m/', verbose_name='Documento')),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.cuentaentrega', verbose_name='Cuenta de entrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor que carga el cierre')),
            ],
            options={
                'verbose_name': 'Documento de cierre',
                'verbose_name_plural': 'Documentos de cierre',
                'constraints': [models.UniqueConstraint(fields=('cuenta_entrega', 'tipo'), name='documento_cierre_unico_por_tipo')],
            },
        ),
        migrations.CreateModel(
            name='RequisitoDocumental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.tipodocumentocargue', verbose_name='Tipo de documento')),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.vigencia', verbose_name='Vigencia')),
            ],
            options={
                'verbose_name': 'Requisito documental',
                'verbose_name_plural': 'Requisitos documentales',
                'constraints': [models.UniqueConstraint(fields=('vigencia', 'tipo_documento'), name='requisito_unico_por_vigencia')],
            },
        ),
    ]
