# Generated by Django 5.2 on 2026-06-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_de_cobro', '0003_roles_cuentas_cobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocierre',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contratista que carga el cierre'),
        ),
        migrations.CreateModel(
            name='TramiteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('EC', 'Entrega de documentos de cierre'), ('SF', 'Cargue en SIIFWEB'), ('SC', 'Cargue en SECOP II')], max_length=2, verbose_name='Tipo de trámite')),
                ('realizado', models.BooleanField(default=False, verbose_name='¿Realizado?')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='tramites_finales/%Y/%m/', verbose_name='Evidencia')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('cuenta_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_finales', to='cuentas_de_cobro.cuentaentrega', verbose_name='Cuenta de entrega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra el trámite')),
            ],
            options={
                'verbose_name': 'Trámite final',
                'verbose_name_plural': 'Trámites finales',
                'constraints': [models.UniqueConstraint(fields=('cuenta_entrega', 'tipo'), name='tramite_final_unico_por_tipo'), models.CheckConstraint(condition=models.Q(('realizado', True), ('evidencia', ''), _connector='OR'), name='evidencia_requiere_realizado')],
            },
        ),
    ]
