# Generated by Django 5.2 on 2026-06-29 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_de_cobro', '0005_roles_radicacion_secop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentocierre',
            name='documento_cierre_unico_por_tipo',
        ),
        migrations.RemoveField(
            model_name='documentocierre',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cuentaentrega',
            name='fecha_aprobacion_supervisor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación supervisor'),
        ),
        migrations.AddField(
            model_name='documentocierre',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cuentas_de_cobro.tipodocumentocargue', verbose_name='Tipo de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentaentrega',
            name='fecha_aprobacion_revisores',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación revisores'),
        ),
        migrations.AlterField(
            model_name='documentocierre',
            name='documento',
            field=models.FileField(upload_to='cierres/%Y/%m/', verbose_name='Documento firmado'),
        ),
        migrations.AlterField(
            model_name='documentocierre',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Rol de radicación que carga el cierre firmado'),
        ),
        migrations.AlterField(
            model_name='tramitefinal',
            name='tipo',
            field=models.CharField(choices=[('SF', 'Cargue en SIIFWEB'), ('SC', 'Cargue en SECOP II')], max_length=2, verbose_name='Tipo de trámite'),
        ),
        migrations.AddConstraint(
            model_name='documentocierre',
            constraint=models.UniqueConstraint(fields=('cuenta_entrega', 'tipo_documento'), name='documento_cierre_unico_por_tipo'),
        ),
    ]
