# Generated by Django 5.2 on 2026-10-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='Con o sin punto, en cualquier caja: se guarda como «.pdf».', max_length=16, unique=True, verbose_name='Extensión')),
                ('activa', models.BooleanField(default=True, help_text='Si se desactiva, deja de admitirse en cargues nuevos.', verbose_name='¿Activa?')),
                ('descripcion', models.CharField(blank=True, help_text='Para quién administra: «Documento de Word», «Hoja de cálculo»…', max_length=120, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extensión de archivo permitida',
                'verbose_name_plural': 'Extensiones de archivo permitidas',
                'ordering': ('extension',),
            },
        ),
    ]
